version: "3.7"

services:
  db-mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    networks:
      - springboot-mysql-net
  springboot-mysql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db-mysql
    networks:
      - springboot-mysql-net
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh db-mysql:3306 -s -t 100
        java -jar /app.jar

networks:
  springboot-mysql-net:
    driver: bridge